### ISSUE TITLE
Doesn't handle when imports are commented out

### ISSUE THREAD

**Issue by cody-dot-js** [dev-cprice/parse-static-imports#8]
example:

```js
// import Foo from 'foo';
/*
import Bar from 'bar';
import Baz from 'baz';
*/
import React, {
//  useState,
  useCallback,
//  useRef,
  useEffect
} from "react";
```

From the above, we should filter out:

- `import Foo from 'foo';`
- `import Bar from 'bar';`
- `import Baz from 'baz';`
- `useState`
- `useRef`

And we should only "see":

```js
import React, {
  useCallback,
  useEffect,
} from "react";
```

**Comment by ivands** [comment]
I still see commented out imports.
How did you fix this?
